# Generated by Django 5.1.6 on 2025-02-12 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='category_nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='product_nomi')),
                ('description', models.TextField(verbose_name='product_haqida')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='narxi')),
                ('discount', models.PositiveSmallIntegerField(verbose_name='foizi')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='product_rasmi')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='product_soni')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
